# Generated by Django 5.2.7 on 2025-10-15 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Freelancer", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="freelancer",
        ),
        migrations.RemoveField(
            model_name="workexperience",
            name="freelancer",
        ),
        migrations.RemoveField(
            model_name="freelancer",
            name="experience",
        ),
        migrations.RemoveField(
            model_name="freelancer",
            name="id",
        ),
        migrations.AddField(
            model_name="freelancer",
            name="education",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="projects",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="work_experience",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="freelancer",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="freelancer_pics/"
            ),
        ),
        migrations.AlterField(
            model_name="freelancer",
            name="social_media_links",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="freelancer",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Education",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="WorkExperience",
        ),
    ]
