# Generated by Django 5.2.7 on 2025-10-24 08:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Freelancer", "0003_alter_freelancer_profile_picture"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="freelancer",
            name="binanceId",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="experience",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="payment_details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="freelancer",
            name="skills",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("contractId", models.CharField(max_length=100)),
                ("review", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enterpriseId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enterprise_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="freelancer",
            name="reviews",
            field=models.ManyToManyField(
                blank=True, related_name="freelancer_reviews", to="Freelancer.reviews"
            ),
        ),
    ]
