# Generated by Django 5.2.7 on 2025-10-16 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Enterprise", "0005_remove_enterprise_id_alter_enterprise_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("job_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("experience", models.CharField(blank=True, max_length=100, null=True)),
                ("required_skills", models.JSONField(blank=True, default=list)),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "pricing_details",
                    models.CharField(
                        choices=[
                            ("dailyRate", "Daily Rate"),
                            ("fixedPrice", "Fixed Price"),
                        ],
                        default="dailyRate",
                        max_length=20,
                    ),
                ),
                (
                    "duration_unit",
                    models.IntegerField(
                        choices=[(1, "Days"), (2, "Weeks"), (3, "Months")]
                    ),
                ),
                ("duration_value", models.IntegerField()),
                ("other_requirements", models.JSONField(blank=True, default=list)),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Enterprise.enterprise",
                    ),
                ),
            ],
        ),
    ]
