# Generated by Django 5.2.7 on 2025-10-27 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Enterprise', '0009_rename_enterprisereview_reviews'),
        ('Freelancer', '0004_freelancer_binanceid_freelancer_experience_and_more'),
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverLetterText', models.TextField(blank=True, null=True)),
                ('coverLetterFileUrl', models.URLField(blank=True, max_length=500, null=True)),
                ('proposedBudget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.IntegerField(choices=[(1, 'Applied'), (2, 'Under Review'), (3, 'Accepted'), (4, 'Rejected')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_received', to='Enterprise.enterprise')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='Freelancer.freelancer')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='Jobs.job')),
            ],
        ),
    ]
