# Generated by Django 5.2.7 on 2025-10-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApply', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='id',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ApplicationId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
