# Generated by Django 5.2.5 on 2025-10-15 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Enterprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "industry_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("contact_person", models.JSONField(blank=True, default=dict)),
                ("location", models.JSONField(blank=True, default=dict)),
                (
                    "preferred_currency",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "preferred_payment_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "vat_or_gst_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("logo", models.URLField(blank=True, null=True)),
                ("social_media_profile", models.URLField(blank=True, null=True)),
                ("previous_projects", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviews", models.ManyToManyField(blank=True, to="Reviews.review")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
