# Generated by Django 5.2.7 on 2025-10-16 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Enterprise", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enterprise",
            name="contact_person",
        ),
        migrations.RemoveField(
            model_name="enterprise",
            name="location",
        ),
        migrations.RemoveField(
            model_name="enterprise",
            name="reviews",
        ),
        migrations.AddField(
            model_name="enterprise",
            name="contact_person_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="contact_person_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="contact_person_phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="location_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="location_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="location_country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="preferred_currency",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="preferred_payment_method",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enterprise_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="vat_or_gst_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
