# Generated by Django 5.2.7 on 2025-10-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Enterprise", "0002_remove_enterprise_contact_person_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprise",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
