# Generated by Django 5.2.7 on 2025-10-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Enterprise", "0003_alter_enterprise_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprise",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/enterprise_logos/"
            ),
        ),
    ]
