# Generated by Django 5.2.7 on 2025-10-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Enterprise", "0005_remove_enterprise_id_alter_enterprise_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enterprise",
            old_name="user",
            new_name="userId",
        ),
        migrations.RemoveField(
            model_name="enterprise",
            name="contact_person_email",
        ),
        migrations.RemoveField(
            model_name="enterprise",
            name="contact_person_name",
        ),
        migrations.RemoveField(
            model_name="enterprise",
            name="contact_person_phone",
        ),
        migrations.RemoveField(
            model_name="enterprise",
            name="location_address",
        ),
        migrations.RemoveField(
            model_name="enterprise",
            name="location_city",
        ),
        migrations.RemoveField(
            model_name="enterprise",
            name="location_country",
        ),
        migrations.AddField(
            model_name="enterprise",
            name="binanceId",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="contactPerson",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="location",
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
    ]
