# Generated by Django 5.2.7 on 2025-10-17 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Enterprise", "0006_rename_user_enterprise_userid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enterprise",
            old_name="userId",
            new_name="user",
        ),
    ]
