# Generated by Django 5.2.7 on 2025-10-24 07:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enterprise', '0007_rename_userid_enterprise_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('contractId', models.CharField(max_length=100)),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freelancerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='enterprise',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='enterprise_reviews', to='Enterprise.enterprisereview'),
        ),
    ]
