# Generated by Django 5.2.7 on 2025-10-24 08:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Enterprise", "0008_enterprisereview_enterprise_reviews"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EnterpriseReview",
            new_name="Reviews",
        ),
    ]
